/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const ampersandCompilerSidebar = require('./docs/Ampersand/sidebar');

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro', // shorthand for a single doc
    'student',
    'software-engineer',
    'interested-visitor',
    { // category
      type: 'category',
      label: 'Ampersand compiler',
      items: ampersandCompilerSidebar.sidebar
    },
  ],
};

module.exports = sidebars;
